name: KCM
channels:
  - https://conda.rosettacommons.org
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - numpy=1.21
  - scipy=1.7.1
  - biopython=1.79
  - pandas=1.3.5
  - matplotlib=3.5.3
  - transformers=4.28.1
  - pyrosetta=2020.10
